# Generated by Django 4.1 on 2024-05-23 12:24

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='movie_image',
            field=models.ImageField(null=True, upload_to=cinema.models.movie_image_path),
        ),
    ]
